# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tony/Desktop/riscv/rv32i_cpu_retiming/rv32i_cpu_retiming.srcs/sources_1/ip/tdpram_2048x32/tdpram_2048x32.xci
# IP: The module: 'tdpram_2048x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tony/Desktop/riscv/rv32i_cpu_retiming/rv32i_cpu_retiming.gen/sources_1/ip/tdpram_2048x32/tdpram_2048x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdpram_2048x32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/tony/Desktop/riscv/rv32i_cpu_retiming/rv32i_cpu_retiming.srcs/sources_1/ip/tdpram_2048x32/tdpram_2048x32.xci
# IP: The module: 'tdpram_2048x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tony/Desktop/riscv/rv32i_cpu_retiming/rv32i_cpu_retiming.gen/sources_1/ip/tdpram_2048x32/tdpram_2048x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdpram_2048x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
