# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tony/Desktop/riscv/rv32i/rv32i.srcs/sources_1/ip/tdpram_4096x32/tdpram_4096x32.xci
# IP: The module: 'tdpram_4096x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tony/Desktop/riscv/rv32i/rv32i.gen/sources_1/ip/tdpram_4096x32/tdpram_4096x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdpram_4096x32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/tony/Desktop/riscv/rv32i/rv32i.srcs/sources_1/ip/tdpram_4096x32/tdpram_4096x32.xci
# IP: The module: 'tdpram_4096x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tony/Desktop/riscv/rv32i/rv32i.gen/sources_1/ip/tdpram_4096x32/tdpram_4096x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdpram_4096x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
