# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/tdpram_4096x32/tdpram_4096x32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tdpram_4096x32 || ORIG_REF_NAME==tdpram_4096x32} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
